version: '3.8'

services:
  qwen2.5-model:
    # Note: This uses Docker's model system
    # First run: docker model pull ai/qwen2.5:3B-Q4_K_M
    # Then run: docker model run -d --name qwen2.5-container -p 8080:8080 ai/qwen2.5:3B-Q4_K_M
    container_name: qwen2.5-container
    ports:
      - "8080:8080"
    environment:
      - MODEL_NAME=qwen2.5-3b
    restart: unless-stopped
    # Uncomment the following lines if you have GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
